# Generated by Django 5.2.7 on 2025-10-14 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tag_remove_song_album_playlist_song_playlist_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='is_private',
        ),
    ]
